export type GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST';
export type GET_FLIGHTS_COMPLETED = 'GET_FLIGHTS_COMPLETED';
export type GET_FLIGHTS_FAILED = 'GET_FLIGHTS_FAILED';

export const GET_FLIGHTS_REQUEST: GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST';
export const GET_FLIGHTS_COMPLETED: GET_FLIGHTS_COMPLETED = 'GET_FLIGHTS_COMPLETED';
export const GET_FLIGHTS_FAILED: GET_FLIGHTS_FAILED = 'GET_FLIGHTS_FAILED';
